# Generated by Django 6.0.5 on 2026-05-28 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Procurement/Fuel File'), ('UTILITY', 'Utility Portal CSV Export'), ('TRAVEL', 'Corporate Travel Platform API/Webhook')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload_backup', models.TextField(help_text='Stores the exact raw string or JSON input data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='emissions.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1: Direct Emissions (e.g., Fuel Combustion)'), ('SCOPE_2', 'Scope 2: Indirect Emissions (e.g., Purchased Electricity)'), ('SCOPE_3', 'Scope 3: Value Chain (e.g., Business Travel, Procurement)')], max_length=15)),
                ('ghg_mapping_category', models.CharField(max_length=100)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_quantity_co2e', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('activity_start_date', models.DateField()),
                ('activity_end_date', models.DateField()),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending Validation Analysis'), ('VALID', 'Passed Structural Validation'), ('SUSPICIOUS', 'Flagged as Anomalous/Suspicious'), ('FAILED', 'Validation Failed (Unparseable/Missing data)')], default='PENDING', max_length=15)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft / Unreviewed'), ('APPROVED', 'Approved & Locked for Audit'), ('REJECTED', 'Rejected / Excluded from Ledger')], default='DRAFT', max_length=15)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('job_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emissions.ingestionjoblog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
            ],
        ),
    ]
